// ============================================================
// TMLSN FITNESS APP — COMPLETE EXERCISE DATABASE
// 150+ exercises with full muscle activation percentages
// ============================================================

import { Exercise } from './types';

// ── CHEST ────────────────────────────────────────────────────

const chestExercises: Exercise[] = [
  {
    id: 'flat_barbell_bench',
    name: 'Flat Barbell Bench Press',
    category: 'chest',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_mid', activationPercent: 85 },
      { muscleId: 'chest_lower', activationPercent: 50 },
      { muscleId: 'chest_upper', activationPercent: 40 },
      { muscleId: 'front_delts', activationPercent: 60 },
      { muscleId: 'triceps_lateral', activationPercent: 55 },
      { muscleId: 'triceps_medial', activationPercent: 40 },
      { muscleId: 'serratus', activationPercent: 20 },
    ],
    description: 'Lie on flat bench, grip bar slightly wider than shoulder width, lower to mid-chest, press up.',
    tips: 'Retract scapula, arch slightly, drive feet into floor.',
  },
  {
    id: 'incline_barbell_bench',
    name: 'Incline Barbell Bench Press',
    category: 'chest',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_upper', activationPercent: 85 },
      { muscleId: 'chest_mid', activationPercent: 55 },
      { muscleId: 'front_delts', activationPercent: 70 },
      { muscleId: 'triceps_lateral', activationPercent: 50 },
      { muscleId: 'triceps_medial', activationPercent: 35 },
      { muscleId: 'serratus', activationPercent: 25 },
    ],
    description: 'Set bench to 30-45°, grip bar slightly wider than shoulders, lower to upper chest, press up.',
    tips: '30° hits more chest, 45° shifts more to delts. Keep scapula retracted.',
  },
  {
    id: 'decline_barbell_bench',
    name: 'Decline Barbell Bench Press',
    category: 'chest',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_lower', activationPercent: 85 },
      { muscleId: 'chest_mid', activationPercent: 65 },
      { muscleId: 'front_delts', activationPercent: 40 },
      { muscleId: 'triceps_lateral', activationPercent: 55 },
      { muscleId: 'triceps_medial', activationPercent: 40 },
    ],
    description: 'Set bench to 15-30° decline, lower bar to lower chest/sternum, press up.',
  },
  {
    id: 'flat_dumbbell_bench',
    name: 'Flat Dumbbell Bench Press',
    category: 'chest',
    equipment: ['dumbbell'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_mid', activationPercent: 90 },
      { muscleId: 'chest_lower', activationPercent: 45 },
      { muscleId: 'chest_upper', activationPercent: 40 },
      { muscleId: 'front_delts', activationPercent: 55 },
      { muscleId: 'triceps_lateral', activationPercent: 45 },
      { muscleId: 'serratus', activationPercent: 25 },
    ],
    description: 'Lie flat, press dumbbells up from chest level with slight arc. Greater ROM than barbell.',
    tips: 'Allows deeper stretch at bottom. Squeeze chest at top.',
  },
  {
    id: 'incline_dumbbell_bench',
    name: 'Incline Dumbbell Bench Press',
    category: 'chest',
    equipment: ['dumbbell'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_upper', activationPercent: 90 },
      { muscleId: 'chest_mid', activationPercent: 50 },
      { muscleId: 'front_delts', activationPercent: 65 },
      { muscleId: 'triceps_lateral', activationPercent: 45 },
      { muscleId: 'serratus', activationPercent: 25 },
    ],
    description: 'Set bench to 30-45°, press dumbbells up from upper chest.',
  },
  {
    id: 'decline_dumbbell_bench',
    name: 'Decline Dumbbell Bench Press',
    category: 'chest',
    equipment: ['dumbbell'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_lower', activationPercent: 90 },
      { muscleId: 'chest_mid', activationPercent: 60 },
      { muscleId: 'front_delts', activationPercent: 35 },
      { muscleId: 'triceps_lateral', activationPercent: 50 },
    ],
    description: 'Set bench to decline, press dumbbells up from lower chest.',
  },
  {
    id: 'flat_dumbbell_fly',
    name: 'Flat Dumbbell Fly',
    category: 'chest',
    equipment: ['dumbbell'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_mid', activationPercent: 90 },
      { muscleId: 'chest_lower', activationPercent: 50 },
      { muscleId: 'chest_upper', activationPercent: 35 },
      { muscleId: 'front_delts', activationPercent: 30 },
      { muscleId: 'biceps_short', activationPercent: 15 },
    ],
    description: 'Lie flat, arms extended with slight bend, lower dumbbells in arc until chest stretch, return.',
  },
  {
    id: 'incline_dumbbell_fly',
    name: 'Incline Dumbbell Fly',
    category: 'chest',
    equipment: ['dumbbell'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_upper', activationPercent: 90 },
      { muscleId: 'chest_mid', activationPercent: 45 },
      { muscleId: 'front_delts', activationPercent: 35 },
      { muscleId: 'biceps_short', activationPercent: 15 },
    ],
    description: 'Set bench to 30°, perform fly motion targeting upper chest.',
  },
  {
    id: 'cable_crossover_high',
    name: 'Cable Crossover (High to Low)',
    category: 'chest',
    equipment: ['cable'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_lower', activationPercent: 85 },
      { muscleId: 'chest_mid', activationPercent: 60 },
      { muscleId: 'front_delts', activationPercent: 25 },
      { muscleId: 'serratus', activationPercent: 20 },
    ],
    description: 'Set cables high, step forward, bring handles down and together in arc.',
  },
  {
    id: 'cable_crossover_low',
    name: 'Cable Crossover (Low to High)',
    category: 'chest',
    equipment: ['cable'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_upper', activationPercent: 85 },
      { muscleId: 'chest_mid', activationPercent: 50 },
      { muscleId: 'front_delts', activationPercent: 35 },
      { muscleId: 'serratus', activationPercent: 25 },
    ],
    description: 'Set cables low, bring handles up and together in arc.',
  },
  {
    id: 'cable_crossover_mid',
    name: 'Cable Crossover (Mid Height)',
    category: 'chest',
    equipment: ['cable'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_mid', activationPercent: 90 },
      { muscleId: 'chest_upper', activationPercent: 40 },
      { muscleId: 'chest_lower', activationPercent: 40 },
      { muscleId: 'front_delts', activationPercent: 25 },
    ],
    description: 'Set cables at chest height, bring handles together at mid-chest.',
  },
  {
    id: 'machine_chest_press',
    name: 'Machine Chest Press',
    category: 'chest',
    equipment: ['machine'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_mid', activationPercent: 80 },
      { muscleId: 'chest_lower', activationPercent: 45 },
      { muscleId: 'front_delts', activationPercent: 50 },
      { muscleId: 'triceps_lateral', activationPercent: 50 },
    ],
    description: 'Seated machine press, push handles forward.',
  },
  {
    id: 'pec_deck',
    name: 'Pec Deck / Machine Fly',
    category: 'chest',
    equipment: ['machine'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_mid', activationPercent: 90 },
      { muscleId: 'chest_upper', activationPercent: 40 },
      { muscleId: 'chest_lower', activationPercent: 40 },
      { muscleId: 'front_delts', activationPercent: 20 },
    ],
    description: 'Sit in pec deck, bring pads together in front of chest.',
  },
  {
    id: 'push_up',
    name: 'Push-Up',
    category: 'chest',
    equipment: ['bodyweight'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_mid', activationPercent: 75 },
      { muscleId: 'chest_lower', activationPercent: 40 },
      { muscleId: 'front_delts', activationPercent: 55 },
      { muscleId: 'triceps_lateral', activationPercent: 55 },
      { muscleId: 'triceps_medial', activationPercent: 40 },
      { muscleId: 'rectus_abdominis', activationPercent: 25 },
      { muscleId: 'serratus', activationPercent: 30 },
    ],
    description: 'Standard push-up from toes, hands shoulder-width, lower chest to floor.',
  },
  {
    id: 'dips_chest',
    name: 'Dips (Chest Focused)',
    category: 'chest',
    equipment: ['bodyweight'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_lower', activationPercent: 85 },
      { muscleId: 'chest_mid', activationPercent: 60 },
      { muscleId: 'front_delts', activationPercent: 55 },
      { muscleId: 'triceps_long', activationPercent: 65 },
      { muscleId: 'triceps_lateral', activationPercent: 55 },
      { muscleId: 'serratus', activationPercent: 20 },
    ],
    description: 'Lean forward on parallel bars, lower until deep chest stretch, press up.',
    tips: 'Lean forward 30° and flare elbows slightly to emphasize chest over triceps.',
  },
  {
    id: 'smith_bench_press',
    name: 'Smith Machine Bench Press',
    category: 'chest',
    equipment: ['smith_machine'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_mid', activationPercent: 80 },
      { muscleId: 'chest_lower', activationPercent: 45 },
      { muscleId: 'front_delts', activationPercent: 55 },
      { muscleId: 'triceps_lateral', activationPercent: 50 },
    ],
    description: 'Bench press on Smith machine. Fixed bar path, good for controlled overload.',
  },
  {
    id: 'landmine_press',
    name: 'Landmine Press',
    category: 'chest',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_upper', activationPercent: 70 },
      { muscleId: 'front_delts', activationPercent: 65 },
      { muscleId: 'triceps_lateral', activationPercent: 40 },
      { muscleId: 'serratus', activationPercent: 35 },
      { muscleId: 'rectus_abdominis', activationPercent: 25 },
    ],
    description: 'Press barbell anchored in landmine attachment up and away from chest.',
  },
  {
    id: 'svend_press',
    name: 'Svend Press',
    category: 'chest',
    equipment: ['plate'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_mid', activationPercent: 80 },
      { muscleId: 'chest_upper', activationPercent: 50 },
      { muscleId: 'front_delts', activationPercent: 30 },
      { muscleId: 'serratus', activationPercent: 20 },
    ],
    description: 'Squeeze two plates together at chest, press forward while maintaining squeeze.',
  },
];

// ── BACK ─────────────────────────────────────────────────────

const backExercises: Exercise[] = [
  {
    id: 'barbell_row',
    name: 'Barbell Bent-Over Row',
    category: 'back',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'lats', activationPercent: 80 },
      { muscleId: 'rhomboids', activationPercent: 75 },
      { muscleId: 'traps_mid', activationPercent: 70 },
      { muscleId: 'traps_lower', activationPercent: 50 },
      { muscleId: 'rear_delts', activationPercent: 55 },
      { muscleId: 'biceps_long', activationPercent: 50 },
      { muscleId: 'biceps_short', activationPercent: 45 },
      { muscleId: 'erector_spinae', activationPercent: 50 },
      { muscleId: 'forearm_flexors', activationPercent: 40 },
    ],
    description: 'Hinge at hips, pull barbell to lower chest/upper abdomen.',
    tips: 'Overhand grip for more upper back, underhand for more lats and biceps.',
  },
  {
    id: 'pendlay_row',
    name: 'Pendlay Row',
    category: 'back',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'lats', activationPercent: 85 },
      { muscleId: 'rhomboids', activationPercent: 75 },
      { muscleId: 'traps_mid', activationPercent: 70 },
      { muscleId: 'rear_delts', activationPercent: 50 },
      { muscleId: 'biceps_long', activationPercent: 45 },
      { muscleId: 'erector_spinae', activationPercent: 55 },
    ],
    description: 'Dead-stop row from floor each rep. Torso parallel, explosive pull.',
  },
  {
    id: 'dumbbell_row',
    name: 'Single-Arm Dumbbell Row',
    category: 'back',
    equipment: ['dumbbell'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'lats', activationPercent: 90 },
      { muscleId: 'teres_major', activationPercent: 65 },
      { muscleId: 'rhomboids', activationPercent: 60 },
      { muscleId: 'traps_mid', activationPercent: 55 },
      { muscleId: 'rear_delts', activationPercent: 50 },
      { muscleId: 'biceps_long', activationPercent: 50 },
      { muscleId: 'forearm_flexors', activationPercent: 40 },
    ],
    description: 'One knee on bench, row dumbbell to hip. Great for lat isolation.',
  },
  {
    id: 'pull_up',
    name: 'Pull-Up',
    category: 'back',
    equipment: ['bodyweight'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'lats', activationPercent: 90 },
      { muscleId: 'teres_major', activationPercent: 70 },
      { muscleId: 'biceps_long', activationPercent: 65 },
      { muscleId: 'biceps_short', activationPercent: 55 },
      { muscleId: 'brachialis', activationPercent: 50 },
      { muscleId: 'rhomboids', activationPercent: 50 },
      { muscleId: 'traps_lower', activationPercent: 45 },
      { muscleId: 'forearm_flexors', activationPercent: 50 },
      { muscleId: 'rectus_abdominis', activationPercent: 20 },
    ],
    description: 'Overhand grip, pull chin above bar. King of back exercises.',
  },
  {
    id: 'chin_up',
    name: 'Chin-Up',
    category: 'back',
    equipment: ['bodyweight'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'lats', activationPercent: 85 },
      { muscleId: 'biceps_long', activationPercent: 80 },
      { muscleId: 'biceps_short', activationPercent: 75 },
      { muscleId: 'brachialis', activationPercent: 55 },
      { muscleId: 'teres_major', activationPercent: 60 },
      { muscleId: 'rhomboids', activationPercent: 45 },
      { muscleId: 'forearm_flexors', activationPercent: 50 },
    ],
    description: 'Underhand grip, pull chin above bar. More bicep emphasis than pull-ups.',
  },
  {
    id: 'neutral_grip_pull_up',
    name: 'Neutral Grip Pull-Up',
    category: 'back',
    equipment: ['bodyweight'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'lats', activationPercent: 85 },
      { muscleId: 'brachialis', activationPercent: 65 },
      { muscleId: 'biceps_long', activationPercent: 60 },
      { muscleId: 'teres_major', activationPercent: 65 },
      { muscleId: 'rhomboids', activationPercent: 50 },
      { muscleId: 'forearm_flexors', activationPercent: 45 },
    ],
    description: 'Palms facing each other, pull up. Easiest on shoulders.',
  },
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    category: 'back',
    equipment: ['cable'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'lats', activationPercent: 85 },
      { muscleId: 'teres_major', activationPercent: 65 },
      { muscleId: 'biceps_long', activationPercent: 55 },
      { muscleId: 'biceps_short', activationPercent: 45 },
      { muscleId: 'rhomboids', activationPercent: 45 },
      { muscleId: 'traps_lower', activationPercent: 40 },
    ],
    description: 'Wide grip, pull bar to upper chest. Lean back slightly.',
  },
  {
    id: 'close_grip_pulldown',
    name: 'Close-Grip Lat Pulldown',
    category: 'back',
    equipment: ['cable'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'lats', activationPercent: 90 },
      { muscleId: 'teres_major', activationPercent: 70 },
      { muscleId: 'biceps_long', activationPercent: 60 },
      { muscleId: 'brachialis', activationPercent: 50 },
      { muscleId: 'rhomboids', activationPercent: 50 },
    ],
    description: 'Narrow V-bar or neutral grip handle, pull to chest.',
  },
  {
    id: 'cable_row_seated',
    name: 'Seated Cable Row',
    category: 'back',
    equipment: ['cable'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'lats', activationPercent: 75 },
      { muscleId: 'rhomboids', activationPercent: 80 },
      { muscleId: 'traps_mid', activationPercent: 75 },
      { muscleId: 'traps_lower', activationPercent: 50 },
      { muscleId: 'rear_delts', activationPercent: 45 },
      { muscleId: 'biceps_long', activationPercent: 50 },
      { muscleId: 'erector_spinae', activationPercent: 35 },
    ],
    description: 'Seated, pull cable handle to lower chest/upper abdomen. Squeeze shoulder blades.',
  },
  {
    id: 'tbar_row',
    name: 'T-Bar Row',
    category: 'back',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'lats', activationPercent: 85 },
      { muscleId: 'rhomboids', activationPercent: 75 },
      { muscleId: 'traps_mid', activationPercent: 70 },
      { muscleId: 'teres_major', activationPercent: 60 },
      { muscleId: 'rear_delts', activationPercent: 50 },
      { muscleId: 'biceps_long', activationPercent: 50 },
      { muscleId: 'erector_spinae', activationPercent: 55 },
    ],
    description: 'Straddle bar in landmine, row to chest with V-handle or overhand grip.',
  },
  {
    id: 'deadlift_conventional',
    name: 'Conventional Deadlift',
    category: 'back',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'hinge',
    muscles: [
      { muscleId: 'erector_spinae', activationPercent: 90 },
      { muscleId: 'glutes_max', activationPercent: 85 },
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 75 },
      { muscleId: 'hamstrings_semitendinosus', activationPercent: 65 },
      { muscleId: 'quads_rectus_femoris', activationPercent: 50 },
      { muscleId: 'quads_vastus_lateralis', activationPercent: 45 },
      { muscleId: 'lats', activationPercent: 50 },
      { muscleId: 'traps_upper', activationPercent: 60 },
      { muscleId: 'traps_mid', activationPercent: 50 },
      { muscleId: 'rhomboids', activationPercent: 40 },
      { muscleId: 'forearm_flexors', activationPercent: 65 },
      { muscleId: 'rectus_abdominis', activationPercent: 40 },
    ],
    description: 'Feet hip-width, grip outside knees, hinge and pull bar up along legs.',
    tips: 'The king of all lifts. Brace core hard, push the floor away.',
  },
  {
    id: 'trap_bar_deadlift',
    name: 'Trap Bar Deadlift',
    category: 'back',
    equipment: ['trap_bar'],
    movementType: 'compound',
    forceType: 'hinge',
    muscles: [
      { muscleId: 'erector_spinae', activationPercent: 80 },
      { muscleId: 'glutes_max', activationPercent: 85 },
      { muscleId: 'quads_rectus_femoris', activationPercent: 65 },
      { muscleId: 'quads_vastus_lateralis', activationPercent: 60 },
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 65 },
      { muscleId: 'traps_upper', activationPercent: 60 },
      { muscleId: 'forearm_flexors', activationPercent: 55 },
    ],
    description: 'Stand inside trap bar, grip handles, stand up. More quad-dominant than conventional.',
  },
  {
    id: 'rack_pull',
    name: 'Rack Pull',
    category: 'back',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'hinge',
    muscles: [
      { muscleId: 'erector_spinae', activationPercent: 85 },
      { muscleId: 'glutes_max', activationPercent: 70 },
      { muscleId: 'traps_upper', activationPercent: 80 },
      { muscleId: 'traps_mid', activationPercent: 65 },
      { muscleId: 'lats', activationPercent: 45 },
      { muscleId: 'forearm_flexors', activationPercent: 70 },
    ],
    description: 'Deadlift from rack pins at knee height. Lockout and upper back focus.',
  },
  {
    id: 'barbell_shrug',
    name: 'Barbell Shrug',
    category: 'back',
    equipment: ['barbell'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'traps_upper', activationPercent: 95 },
      { muscleId: 'traps_mid', activationPercent: 50 },
      { muscleId: 'forearm_flexors', activationPercent: 35 },
    ],
    description: 'Hold barbell at waist, shrug shoulders straight up toward ears.',
  },
  {
    id: 'dumbbell_shrug',
    name: 'Dumbbell Shrug',
    category: 'back',
    equipment: ['dumbbell'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'traps_upper', activationPercent: 95 },
      { muscleId: 'traps_mid', activationPercent: 45 },
      { muscleId: 'forearm_flexors', activationPercent: 40 },
    ],
    description: 'Hold dumbbells at sides, shrug shoulders up. Greater ROM than barbell.',
  },
  {
    id: 'face_pull',
    name: 'Face Pull',
    category: 'back',
    equipment: ['cable'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'rear_delts', activationPercent: 85 },
      { muscleId: 'rhomboids', activationPercent: 70 },
      { muscleId: 'traps_mid', activationPercent: 65 },
      { muscleId: 'traps_lower', activationPercent: 45 },
      { muscleId: 'rotator_cuff', activationPercent: 60 },
    ],
    description: 'Pull rope attachment to face, externally rotate at end. Essential for shoulder health.',
    tips: 'Should be in every program. Pull apart at the end for external rotation.',
  },
  {
    id: 'straight_arm_pulldown',
    name: 'Straight-Arm Pulldown',
    category: 'back',
    equipment: ['cable'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'lats', activationPercent: 90 },
      { muscleId: 'teres_major', activationPercent: 70 },
      { muscleId: 'traps_lower', activationPercent: 40 },
      { muscleId: 'triceps_long', activationPercent: 30 },
      { muscleId: 'rectus_abdominis', activationPercent: 20 },
    ],
    description: 'Arms straight, pull bar/rope down in arc from overhead to thighs.',
  },
  {
    id: 'machine_row',
    name: 'Machine Row (Chest-Supported)',
    category: 'back',
    equipment: ['machine'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'lats', activationPercent: 80 },
      { muscleId: 'rhomboids', activationPercent: 75 },
      { muscleId: 'traps_mid', activationPercent: 70 },
      { muscleId: 'rear_delts', activationPercent: 50 },
      { muscleId: 'biceps_long', activationPercent: 45 },
    ],
    description: 'Chest against pad, row handles back. Eliminates momentum/cheating.',
  },
  {
    id: 'chest_supported_dumbbell_row',
    name: 'Chest-Supported Dumbbell Row',
    category: 'back',
    equipment: ['dumbbell'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'lats', activationPercent: 80 },
      { muscleId: 'rhomboids', activationPercent: 75 },
      { muscleId: 'traps_mid', activationPercent: 65 },
      { muscleId: 'rear_delts', activationPercent: 55 },
      { muscleId: 'biceps_long', activationPercent: 50 },
    ],
    description: 'Lie chest-down on incline bench, row dumbbells up. Strict form, no cheating.',
  },
  {
    id: 'meadows_row',
    name: 'Meadows Row',
    category: 'back',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'lats', activationPercent: 90 },
      { muscleId: 'teres_major', activationPercent: 70 },
      { muscleId: 'rear_delts', activationPercent: 50 },
      { muscleId: 'rhomboids', activationPercent: 55 },
      { muscleId: 'biceps_long', activationPercent: 45 },
      { muscleId: 'forearm_flexors', activationPercent: 50 },
    ],
    description: 'Stand perpendicular to landmine, overhand grip end of bar, row to hip.',
  },
  {
    id: 'back_extension',
    name: 'Back Extension / Hyperextension',
    category: 'back',
    equipment: ['bodyweight'],
    movementType: 'isolation',
    forceType: 'hinge',
    muscles: [
      { muscleId: 'erector_spinae', activationPercent: 90 },
      { muscleId: 'glutes_max', activationPercent: 60 },
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 50 },
    ],
    description: 'On hyperextension bench, lower torso, extend back up to neutral.',
  },
  {
    id: 'inverted_row',
    name: 'Inverted Row',
    category: 'back',
    equipment: ['bodyweight'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'lats', activationPercent: 70 },
      { muscleId: 'rhomboids', activationPercent: 75 },
      { muscleId: 'traps_mid', activationPercent: 65 },
      { muscleId: 'rear_delts', activationPercent: 55 },
      { muscleId: 'biceps_long', activationPercent: 50 },
      { muscleId: 'rectus_abdominis', activationPercent: 25 },
    ],
    description: 'Under a bar at waist height, pull chest to bar. Bodyweight horizontal pull.',
  },
];

// ── SHOULDERS ────────────────────────────────────────────────

const shoulderExercises: Exercise[] = [
  {
    id: 'overhead_press',
    name: 'Barbell Overhead Press',
    category: 'shoulders',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'front_delts', activationPercent: 90 },
      { muscleId: 'side_delts', activationPercent: 55 },
      { muscleId: 'triceps_long', activationPercent: 60 },
      { muscleId: 'triceps_lateral', activationPercent: 55 },
      { muscleId: 'traps_upper', activationPercent: 50 },
      { muscleId: 'chest_upper', activationPercent: 30 },
      { muscleId: 'rectus_abdominis', activationPercent: 30 },
      { muscleId: 'erector_spinae', activationPercent: 25 },
    ],
    description: 'Standing, press barbell from shoulders to overhead lockout.',
    tips: 'Squeeze glutes and brace core. Push head through at the top.',
  },
  {
    id: 'push_press',
    name: 'Push Press',
    category: 'shoulders',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'front_delts', activationPercent: 85 },
      { muscleId: 'side_delts', activationPercent: 50 },
      { muscleId: 'triceps_long', activationPercent: 55 },
      { muscleId: 'triceps_lateral', activationPercent: 50 },
      { muscleId: 'quads_rectus_femoris', activationPercent: 35 },
      { muscleId: 'glutes_max', activationPercent: 30 },
      { muscleId: 'traps_upper', activationPercent: 50 },
    ],
    description: 'Slight knee dip for leg drive, then press barbell overhead explosively.',
  },
  {
    id: 'dumbbell_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    category: 'shoulders',
    equipment: ['dumbbell'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'front_delts', activationPercent: 85 },
      { muscleId: 'side_delts', activationPercent: 60 },
      { muscleId: 'triceps_long', activationPercent: 55 },
      { muscleId: 'triceps_lateral', activationPercent: 50 },
      { muscleId: 'traps_upper', activationPercent: 45 },
    ],
    description: 'Seated or standing, press dumbbells from shoulders to overhead.',
  },
  {
    id: 'arnold_press',
    name: 'Arnold Press',
    category: 'shoulders',
    equipment: ['dumbbell'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'front_delts', activationPercent: 85 },
      { muscleId: 'side_delts', activationPercent: 70 },
      { muscleId: 'rear_delts', activationPercent: 30 },
      { muscleId: 'triceps_long', activationPercent: 50 },
      { muscleId: 'traps_upper', activationPercent: 40 },
    ],
    description: 'Start palms facing you, rotate outward while pressing overhead.',
    tips: 'The rotation hits all three delt heads through a full range.',
  },
  {
    id: 'lateral_raise_dumbbell',
    name: 'Dumbbell Lateral Raise',
    category: 'shoulders',
    equipment: ['dumbbell'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'side_delts', activationPercent: 95 },
      { muscleId: 'front_delts', activationPercent: 25 },
      { muscleId: 'traps_upper', activationPercent: 35 },
    ],
    description: 'Arms at sides, raise dumbbells laterally to shoulder height.',
    tips: 'Slight lean forward, lead with elbows, pour the teacup at top.',
  },
  {
    id: 'lateral_raise_cable',
    name: 'Cable Lateral Raise',
    category: 'shoulders',
    equipment: ['cable'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'side_delts', activationPercent: 95 },
      { muscleId: 'front_delts', activationPercent: 20 },
      { muscleId: 'traps_upper', activationPercent: 30 },
    ],
    description: 'Single-arm cable raise from low pulley. Constant tension throughout.',
  },
  {
    id: 'machine_lateral_raise',
    name: 'Machine Lateral Raise',
    category: 'shoulders',
    equipment: ['machine'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'side_delts', activationPercent: 90 },
      { muscleId: 'front_delts', activationPercent: 20 },
      { muscleId: 'traps_upper', activationPercent: 30 },
    ],
    description: 'Seated machine, push pads up laterally with elbows.',
  },
  {
    id: 'front_raise_dumbbell',
    name: 'Dumbbell Front Raise',
    category: 'shoulders',
    equipment: ['dumbbell'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'front_delts', activationPercent: 90 },
      { muscleId: 'side_delts', activationPercent: 25 },
      { muscleId: 'chest_upper', activationPercent: 20 },
      { muscleId: 'serratus', activationPercent: 15 },
    ],
    description: 'Raise dumbbell in front to shoulder height, one or both arms.',
  },
  {
    id: 'rear_delt_fly_dumbbell',
    name: 'Dumbbell Rear Delt Fly',
    category: 'shoulders',
    equipment: ['dumbbell'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'rear_delts', activationPercent: 90 },
      { muscleId: 'rhomboids', activationPercent: 50 },
      { muscleId: 'traps_mid', activationPercent: 45 },
      { muscleId: 'rotator_cuff', activationPercent: 30 },
    ],
    description: 'Bent over, raise dumbbells laterally to target rear delts.',
  },
  {
    id: 'rear_delt_fly_machine',
    name: 'Reverse Pec Deck / Rear Delt Machine',
    category: 'shoulders',
    equipment: ['machine'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'rear_delts', activationPercent: 90 },
      { muscleId: 'rhomboids', activationPercent: 50 },
      { muscleId: 'traps_mid', activationPercent: 45 },
    ],
    description: 'Reverse the pec deck, push pads backward. Targets rear delts.',
  },
  {
    id: 'rear_delt_cable_fly',
    name: 'Cable Rear Delt Fly',
    category: 'shoulders',
    equipment: ['cable'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'rear_delts', activationPercent: 90 },
      { muscleId: 'rhomboids', activationPercent: 45 },
      { muscleId: 'traps_mid', activationPercent: 40 },
      { muscleId: 'rotator_cuff', activationPercent: 30 },
    ],
    description: 'Cross cables at face height, pull outward with straight arms.',
  },
  {
    id: 'upright_row',
    name: 'Upright Row',
    category: 'shoulders',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'side_delts', activationPercent: 80 },
      { muscleId: 'front_delts', activationPercent: 50 },
      { muscleId: 'traps_upper', activationPercent: 75 },
      { muscleId: 'biceps_short', activationPercent: 30 },
    ],
    description: 'Pull barbell up along body to chin, elbows leading.',
    tips: 'Wide grip = more delts, narrow grip = more traps. Watch shoulder impingement.',
  },
  {
    id: 'cable_upright_row',
    name: 'Cable Upright Row',
    category: 'shoulders',
    equipment: ['cable'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'side_delts', activationPercent: 80 },
      { muscleId: 'front_delts', activationPercent: 45 },
      { muscleId: 'traps_upper', activationPercent: 70 },
      { muscleId: 'biceps_short', activationPercent: 25 },
    ],
    description: 'Cable version of upright row. Constant tension.',
  },
  {
    id: 'machine_shoulder_press',
    name: 'Machine Shoulder Press',
    category: 'shoulders',
    equipment: ['machine'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'front_delts', activationPercent: 80 },
      { muscleId: 'side_delts', activationPercent: 50 },
      { muscleId: 'triceps_long', activationPercent: 50 },
      { muscleId: 'triceps_lateral', activationPercent: 45 },
    ],
    description: 'Seated machine overhead press. Guided path, good for overloading.',
  },
  {
    id: 'lu_raise',
    name: 'Lu Raise',
    category: 'shoulders',
    equipment: ['plate'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'front_delts', activationPercent: 80 },
      { muscleId: 'side_delts', activationPercent: 65 },
      { muscleId: 'traps_upper', activationPercent: 40 },
      { muscleId: 'serratus', activationPercent: 30 },
    ],
    description: 'Hold plate, raise from thighs to overhead in one fluid motion.',
  },
];

// ── BICEPS ───────────────────────────────────────────────────

const bicepsExercises: Exercise[] = [
  {
    id: 'barbell_curl',
    name: 'Barbell Curl',
    category: 'biceps',
    equipment: ['barbell'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'biceps_short', activationPercent: 90 },
      { muscleId: 'biceps_long', activationPercent: 85 },
      { muscleId: 'brachialis', activationPercent: 50 },
      { muscleId: 'brachioradialis', activationPercent: 40 },
      { muscleId: 'forearm_flexors', activationPercent: 35 },
    ],
    description: 'Standing, curl barbell from thighs to shoulders.',
  },
  {
    id: 'ez_bar_curl',
    name: 'EZ Bar Curl',
    category: 'biceps',
    equipment: ['ez_bar'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'biceps_short', activationPercent: 85 },
      { muscleId: 'biceps_long', activationPercent: 85 },
      { muscleId: 'brachialis', activationPercent: 55 },
      { muscleId: 'brachioradialis', activationPercent: 45 },
    ],
    description: 'Curl EZ bar. Angled grip is easier on wrists.',
  },
  {
    id: 'dumbbell_curl',
    name: 'Dumbbell Curl',
    category: 'biceps',
    equipment: ['dumbbell'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'biceps_short', activationPercent: 85 },
      { muscleId: 'biceps_long', activationPercent: 85 },
      { muscleId: 'brachialis', activationPercent: 45 },
      { muscleId: 'forearm_flexors', activationPercent: 35 },
    ],
    description: 'Standing or seated, curl dumbbells alternating or together.',
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    category: 'biceps',
    equipment: ['dumbbell'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'brachialis', activationPercent: 85 },
      { muscleId: 'brachioradialis', activationPercent: 80 },
      { muscleId: 'biceps_long', activationPercent: 65 },
      { muscleId: 'forearm_flexors', activationPercent: 45 },
    ],
    description: 'Neutral grip (palms facing in), curl dumbbells. Great for arm thickness.',
    tips: 'Targets brachialis which pushes the bicep up — key for arm size.',
  },
  {
    id: 'incline_dumbbell_curl',
    name: 'Incline Dumbbell Curl',
    category: 'biceps',
    equipment: ['dumbbell'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'biceps_long', activationPercent: 95 },
      { muscleId: 'biceps_short', activationPercent: 70 },
      { muscleId: 'brachialis', activationPercent: 40 },
    ],
    description: 'Seated on incline bench (45°), curl from full stretch. Maximal long head stretch.',
    tips: 'Best exercise for the biceps long head (peak).',
  },
  {
    id: 'preacher_curl',
    name: 'Preacher Curl',
    category: 'biceps',
    equipment: ['ez_bar'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'biceps_short', activationPercent: 95 },
      { muscleId: 'biceps_long', activationPercent: 70 },
      { muscleId: 'brachialis', activationPercent: 60 },
    ],
    description: 'Arms on preacher pad, curl. Eliminates momentum, short head emphasis.',
  },
  {
    id: 'concentration_curl',
    name: 'Concentration Curl',
    category: 'biceps',
    equipment: ['dumbbell'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'biceps_short', activationPercent: 90 },
      { muscleId: 'biceps_long', activationPercent: 80 },
      { muscleId: 'brachialis', activationPercent: 50 },
    ],
    description: 'Seated, elbow braced against inner thigh, curl with focus on peak contraction.',
  },
  {
    id: 'cable_curl',
    name: 'Cable Curl',
    category: 'biceps',
    equipment: ['cable'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'biceps_short', activationPercent: 85 },
      { muscleId: 'biceps_long', activationPercent: 85 },
      { muscleId: 'brachialis', activationPercent: 45 },
      { muscleId: 'forearm_flexors', activationPercent: 30 },
    ],
    description: 'Stand facing low cable, curl bar or rope handle up.',
  },
  {
    id: 'bayesian_curl',
    name: 'Bayesian Cable Curl',
    category: 'biceps',
    equipment: ['cable'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'biceps_long', activationPercent: 95 },
      { muscleId: 'biceps_short', activationPercent: 65 },
      { muscleId: 'brachialis', activationPercent: 35 },
    ],
    description: 'Face away from cable, arm behind body, curl. Maximal long head stretch under load.',
    tips: 'One of the best long head exercises due to shoulder extension + curl.',
  },
  {
    id: 'spider_curl',
    name: 'Spider Curl',
    category: 'biceps',
    equipment: ['dumbbell'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'biceps_short', activationPercent: 95 },
      { muscleId: 'biceps_long', activationPercent: 75 },
      { muscleId: 'brachialis', activationPercent: 55 },
    ],
    description: 'Lean chest-down on incline bench, curl from hanging position. Peak contraction focus.',
  },
  {
    id: 'cross_body_hammer_curl',
    name: 'Cross-Body Hammer Curl',
    category: 'biceps',
    equipment: ['dumbbell'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'brachialis', activationPercent: 80 },
      { muscleId: 'brachioradialis', activationPercent: 75 },
      { muscleId: 'biceps_long', activationPercent: 55 },
      { muscleId: 'forearm_flexors', activationPercent: 40 },
    ],
    description: 'Hammer curl across the body toward opposite shoulder.',
  },
  {
    id: 'machine_curl',
    name: 'Machine Bicep Curl',
    category: 'biceps',
    equipment: ['machine'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'biceps_short', activationPercent: 85 },
      { muscleId: 'biceps_long', activationPercent: 80 },
      { muscleId: 'brachialis', activationPercent: 45 },
    ],
    description: 'Seated machine curl. Fixed path, good for burnouts.',
  },
];

// ── TRICEPS ──────────────────────────────────────────────────

const tricepsExercises: Exercise[] = [
  {
    id: 'close_grip_bench',
    name: 'Close-Grip Bench Press',
    category: 'triceps',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'triceps_long', activationPercent: 80 },
      { muscleId: 'triceps_lateral', activationPercent: 80 },
      { muscleId: 'triceps_medial', activationPercent: 70 },
      { muscleId: 'chest_mid', activationPercent: 55 },
      { muscleId: 'front_delts', activationPercent: 40 },
    ],
    description: 'Bench press with hands shoulder-width or narrower.',
  },
  {
    id: 'skull_crusher',
    name: 'Skull Crusher / Lying Tricep Extension',
    category: 'triceps',
    equipment: ['ez_bar'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'triceps_long', activationPercent: 90 },
      { muscleId: 'triceps_lateral', activationPercent: 70 },
      { muscleId: 'triceps_medial', activationPercent: 65 },
    ],
    description: 'Lying on bench, lower bar to forehead or behind head, extend arms.',
    tips: 'Lowering behind the head increases long head stretch.',
  },
  {
    id: 'tricep_pushdown_rope',
    name: 'Tricep Pushdown (Rope)',
    category: 'triceps',
    equipment: ['cable'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'triceps_lateral', activationPercent: 90 },
      { muscleId: 'triceps_medial', activationPercent: 75 },
      { muscleId: 'triceps_long', activationPercent: 55 },
    ],
    description: 'Push rope down and split at bottom for peak contraction.',
  },
  {
    id: 'tricep_pushdown_bar',
    name: 'Tricep Pushdown (Straight Bar)',
    category: 'triceps',
    equipment: ['cable'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'triceps_lateral', activationPercent: 90 },
      { muscleId: 'triceps_medial', activationPercent: 80 },
      { muscleId: 'triceps_long', activationPercent: 50 },
    ],
    description: 'Push straight bar down, lock out elbows.',
  },
  {
    id: 'overhead_tricep_extension_cable',
    name: 'Overhead Cable Tricep Extension',
    category: 'triceps',
    equipment: ['cable'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'triceps_long', activationPercent: 95 },
      { muscleId: 'triceps_lateral', activationPercent: 55 },
      { muscleId: 'triceps_medial', activationPercent: 50 },
    ],
    description: 'Face away from cable, extend rope overhead. Best long head exercise.',
    tips: 'The long head is the biggest tricep head — this should be a staple.',
  },
  {
    id: 'overhead_dumbbell_extension',
    name: 'Overhead Dumbbell Tricep Extension',
    category: 'triceps',
    equipment: ['dumbbell'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'triceps_long', activationPercent: 90 },
      { muscleId: 'triceps_lateral', activationPercent: 50 },
      { muscleId: 'triceps_medial', activationPercent: 45 },
    ],
    description: 'Hold dumbbell overhead with both hands, lower behind head, extend.',
  },
  {
    id: 'dips_triceps',
    name: 'Dips (Triceps Focused)',
    category: 'triceps',
    equipment: ['bodyweight'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'triceps_long', activationPercent: 80 },
      { muscleId: 'triceps_lateral', activationPercent: 75 },
      { muscleId: 'triceps_medial', activationPercent: 65 },
      { muscleId: 'chest_lower', activationPercent: 45 },
      { muscleId: 'front_delts', activationPercent: 45 },
    ],
    description: 'Upright torso on parallel bars, dip and press. Elbows close.',
    tips: 'Stay upright and elbows close to emphasize triceps over chest.',
  },
  {
    id: 'kickback_dumbbell',
    name: 'Dumbbell Kickback',
    category: 'triceps',
    equipment: ['dumbbell'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'triceps_lateral', activationPercent: 85 },
      { muscleId: 'triceps_long', activationPercent: 60 },
      { muscleId: 'triceps_medial', activationPercent: 55 },
    ],
    description: 'Bent over, elbow pinned at side, extend forearm behind.',
  },
  {
    id: 'diamond_push_up',
    name: 'Diamond Push-Up',
    category: 'triceps',
    equipment: ['bodyweight'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'triceps_lateral', activationPercent: 85 },
      { muscleId: 'triceps_long', activationPercent: 70 },
      { muscleId: 'triceps_medial', activationPercent: 65 },
      { muscleId: 'chest_mid', activationPercent: 55 },
      { muscleId: 'front_delts', activationPercent: 45 },
    ],
    description: 'Push-up with hands close together in diamond shape.',
  },
  {
    id: 'jm_press',
    name: 'JM Press',
    category: 'triceps',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'triceps_long', activationPercent: 85 },
      { muscleId: 'triceps_lateral', activationPercent: 80 },
      { muscleId: 'triceps_medial', activationPercent: 70 },
      { muscleId: 'chest_mid', activationPercent: 30 },
    ],
    description: 'Hybrid between close-grip bench and skull crusher. Lower to chin, press up.',
  },
];

// ── FOREARMS ─────────────────────────────────────────────────

const forearmExercises: Exercise[] = [
  {
    id: 'wrist_curl_barbell',
    name: 'Barbell Wrist Curl',
    category: 'forearms',
    equipment: ['barbell'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'forearm_flexors', activationPercent: 95 },
    ],
    description: 'Seated, forearms on thighs, curl bar with wrists only.',
  },
  {
    id: 'reverse_wrist_curl',
    name: 'Reverse Wrist Curl',
    category: 'forearms',
    equipment: ['barbell'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'forearm_extensors', activationPercent: 95 },
    ],
    description: 'Palms down, curl bar upward with wrists only.',
  },
  {
    id: 'reverse_curl',
    name: 'Reverse Curl',
    category: 'forearms',
    equipment: ['ez_bar'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'brachioradialis', activationPercent: 90 },
      { muscleId: 'forearm_extensors', activationPercent: 65 },
      { muscleId: 'brachialis', activationPercent: 60 },
      { muscleId: 'biceps_long', activationPercent: 40 },
    ],
    description: 'Curl with palms facing down (pronated grip).',
  },
  {
    id: 'farmer_walk',
    name: "Farmer's Walk",
    category: 'forearms',
    equipment: ['dumbbell'],
    movementType: 'compound',
    forceType: 'static',
    muscles: [
      { muscleId: 'forearm_flexors', activationPercent: 90 },
      { muscleId: 'traps_upper', activationPercent: 70 },
      { muscleId: 'rectus_abdominis', activationPercent: 50 },
      { muscleId: 'obliques', activationPercent: 50 },
      { muscleId: 'erector_spinae', activationPercent: 45 },
      { muscleId: 'calves_gastrocnemius', activationPercent: 30 },
    ],
    description: 'Hold heavy dumbbells/implements, walk for distance or time.',
  },
  {
    id: 'dead_hang',
    name: 'Dead Hang',
    category: 'forearms',
    equipment: ['bodyweight'],
    movementType: 'isolation',
    forceType: 'static',
    muscles: [
      { muscleId: 'forearm_flexors', activationPercent: 85 },
      { muscleId: 'lats', activationPercent: 20 },
      { muscleId: 'traps_lower', activationPercent: 15 },
    ],
    description: 'Hang from pull-up bar for max time. Great for grip and spinal decompression.',
  },
];

// ── LEGS: QUADS ──────────────────────────────────────────────

const quadExercises: Exercise[] = [
  {
    id: 'back_squat',
    name: 'Barbell Back Squat',
    category: 'quads',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'legs',
    muscles: [
      { muscleId: 'quads_rectus_femoris', activationPercent: 85 },
      { muscleId: 'quads_vastus_lateralis', activationPercent: 90 },
      { muscleId: 'quads_vastus_medialis', activationPercent: 85 },
      { muscleId: 'quads_vastus_intermedius', activationPercent: 80 },
      { muscleId: 'glutes_max', activationPercent: 75 },
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 40 },
      { muscleId: 'erector_spinae', activationPercent: 55 },
      { muscleId: 'rectus_abdominis', activationPercent: 40 },
      { muscleId: 'adductors', activationPercent: 45 },
    ],
    description: 'Bar on upper back, squat to at least parallel. The king of leg exercises.',
    tips: 'High bar = more quads, low bar = more posterior chain. Squat deep.',
  },
  {
    id: 'front_squat',
    name: 'Front Squat',
    category: 'quads',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'legs',
    muscles: [
      { muscleId: 'quads_rectus_femoris', activationPercent: 95 },
      { muscleId: 'quads_vastus_lateralis', activationPercent: 90 },
      { muscleId: 'quads_vastus_medialis', activationPercent: 90 },
      { muscleId: 'quads_vastus_intermedius', activationPercent: 85 },
      { muscleId: 'glutes_max', activationPercent: 60 },
      { muscleId: 'rectus_abdominis', activationPercent: 55 },
      { muscleId: 'erector_spinae', activationPercent: 50 },
    ],
    description: 'Bar racked on front delts, squat deep. More quad-dominant and upright.',
  },
  {
    id: 'goblet_squat',
    name: 'Goblet Squat',
    category: 'quads',
    equipment: ['dumbbell', 'kettlebell'],
    movementType: 'compound',
    forceType: 'legs',
    muscles: [
      { muscleId: 'quads_rectus_femoris', activationPercent: 80 },
      { muscleId: 'quads_vastus_lateralis', activationPercent: 80 },
      { muscleId: 'quads_vastus_medialis', activationPercent: 80 },
      { muscleId: 'glutes_max', activationPercent: 65 },
      { muscleId: 'rectus_abdominis', activationPercent: 35 },
    ],
    description: 'Hold dumbbell/kettlebell at chest, squat deep.',
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    category: 'quads',
    equipment: ['machine'],
    movementType: 'compound',
    forceType: 'legs',
    muscles: [
      { muscleId: 'quads_rectus_femoris', activationPercent: 85 },
      { muscleId: 'quads_vastus_lateralis', activationPercent: 85 },
      { muscleId: 'quads_vastus_medialis', activationPercent: 85 },
      { muscleId: 'glutes_max', activationPercent: 60 },
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 30 },
      { muscleId: 'adductors', activationPercent: 35 },
    ],
    description: 'Seated machine, press platform away. Foot position changes emphasis.',
    tips: 'Feet low + narrow = more quads. Feet high + wide = more glutes/hams.',
  },
  {
    id: 'hack_squat',
    name: 'Hack Squat',
    category: 'quads',
    equipment: ['machine'],
    movementType: 'compound',
    forceType: 'legs',
    muscles: [
      { muscleId: 'quads_rectus_femoris', activationPercent: 90 },
      { muscleId: 'quads_vastus_lateralis', activationPercent: 90 },
      { muscleId: 'quads_vastus_medialis', activationPercent: 90 },
      { muscleId: 'glutes_max', activationPercent: 55 },
    ],
    description: 'Machine squat with back against pad. Quad-focused.',
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension',
    category: 'quads',
    equipment: ['machine'],
    movementType: 'isolation',
    forceType: 'legs',
    muscles: [
      { muscleId: 'quads_rectus_femoris', activationPercent: 95 },
      { muscleId: 'quads_vastus_lateralis', activationPercent: 90 },
      { muscleId: 'quads_vastus_medialis', activationPercent: 90 },
      { muscleId: 'quads_vastus_intermedius', activationPercent: 85 },
    ],
    description: 'Seated, extend legs. Pure quad isolation.',
  },
  {
    id: 'walking_lunge',
    name: 'Walking Lunge',
    category: 'quads',
    equipment: ['dumbbell', 'bodyweight'],
    movementType: 'compound',
    forceType: 'legs',
    muscles: [
      { muscleId: 'quads_rectus_femoris', activationPercent: 80 },
      { muscleId: 'quads_vastus_lateralis', activationPercent: 80 },
      { muscleId: 'glutes_max', activationPercent: 70 },
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 40 },
      { muscleId: 'adductors', activationPercent: 35 },
      { muscleId: 'rectus_abdominis', activationPercent: 25 },
    ],
    description: 'Step forward, lower back knee toward ground, push off front foot.',
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    category: 'quads',
    equipment: ['dumbbell', 'bodyweight'],
    movementType: 'compound',
    forceType: 'legs',
    muscles: [
      { muscleId: 'quads_rectus_femoris', activationPercent: 85 },
      { muscleId: 'quads_vastus_lateralis', activationPercent: 85 },
      { muscleId: 'quads_vastus_medialis', activationPercent: 85 },
      { muscleId: 'glutes_max', activationPercent: 75 },
      { muscleId: 'glutes_med', activationPercent: 40 },
      { muscleId: 'adductors', activationPercent: 35 },
      { muscleId: 'hip_flexors', activationPercent: 30 },
    ],
    description: 'Rear foot elevated on bench, lunge down on front leg.',
    tips: 'Arguably the best unilateral leg exercise. Great for fixing imbalances.',
  },
  {
    id: 'sissy_squat',
    name: 'Sissy Squat',
    category: 'quads',
    equipment: ['bodyweight'],
    movementType: 'isolation',
    forceType: 'legs',
    muscles: [
      { muscleId: 'quads_rectus_femoris', activationPercent: 95 },
      { muscleId: 'quads_vastus_lateralis', activationPercent: 85 },
      { muscleId: 'quads_vastus_medialis', activationPercent: 90 },
      { muscleId: 'hip_flexors', activationPercent: 30 },
    ],
    description: 'Lean back, knees forward, lower body while staying on toes. Pure quad burn.',
  },
  {
    id: 'smith_squat',
    name: 'Smith Machine Squat',
    category: 'quads',
    equipment: ['smith_machine'],
    movementType: 'compound',
    forceType: 'legs',
    muscles: [
      { muscleId: 'quads_rectus_femoris', activationPercent: 85 },
      { muscleId: 'quads_vastus_lateralis', activationPercent: 85 },
      { muscleId: 'quads_vastus_medialis', activationPercent: 85 },
      { muscleId: 'glutes_max', activationPercent: 65 },
    ],
    description: 'Squat on Smith machine. Feet forward placement isolates quads more.',
  },
  {
    id: 'step_up',
    name: 'Step-Up',
    category: 'quads',
    equipment: ['dumbbell', 'bodyweight'],
    movementType: 'compound',
    forceType: 'legs',
    muscles: [
      { muscleId: 'quads_rectus_femoris', activationPercent: 75 },
      { muscleId: 'quads_vastus_lateralis', activationPercent: 75 },
      { muscleId: 'glutes_max', activationPercent: 70 },
      { muscleId: 'glutes_med', activationPercent: 40 },
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 30 },
    ],
    description: 'Step onto elevated platform, drive through front leg.',
  },
];

// ── LEGS: HAMSTRINGS ─────────────────────────────────────────

const hamstringExercises: Exercise[] = [
  {
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift (RDL)',
    category: 'hamstrings',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'hinge',
    muscles: [
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 90 },
      { muscleId: 'hamstrings_semitendinosus', activationPercent: 85 },
      { muscleId: 'hamstrings_semimembranosus', activationPercent: 85 },
      { muscleId: 'glutes_max', activationPercent: 75 },
      { muscleId: 'erector_spinae', activationPercent: 70 },
      { muscleId: 'forearm_flexors', activationPercent: 40 },
    ],
    description: 'Hinge at hips, bar slides down thighs, deep hamstring stretch, return.',
    tips: 'Keep bar close, push hips back, slight knee bend. Feel the stretch.',
  },
  {
    id: 'dumbbell_rdl',
    name: 'Dumbbell RDL',
    category: 'hamstrings',
    equipment: ['dumbbell'],
    movementType: 'compound',
    forceType: 'hinge',
    muscles: [
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 85 },
      { muscleId: 'hamstrings_semitendinosus', activationPercent: 80 },
      { muscleId: 'glutes_max', activationPercent: 75 },
      { muscleId: 'erector_spinae', activationPercent: 60 },
    ],
    description: 'RDL with dumbbells. More freedom of movement than barbell.',
  },
  {
    id: 'single_leg_rdl',
    name: 'Single-Leg RDL',
    category: 'hamstrings',
    equipment: ['dumbbell'],
    movementType: 'compound',
    forceType: 'hinge',
    muscles: [
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 85 },
      { muscleId: 'hamstrings_semitendinosus', activationPercent: 80 },
      { muscleId: 'glutes_max', activationPercent: 80 },
      { muscleId: 'glutes_med', activationPercent: 55 },
      { muscleId: 'erector_spinae', activationPercent: 50 },
      { muscleId: 'rectus_abdominis', activationPercent: 30 },
    ],
    description: 'RDL on one leg. Great for balance and unilateral strength.',
  },
  {
    id: 'lying_leg_curl',
    name: 'Lying Leg Curl',
    category: 'hamstrings',
    equipment: ['machine'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 90 },
      { muscleId: 'hamstrings_semitendinosus', activationPercent: 90 },
      { muscleId: 'hamstrings_semimembranosus', activationPercent: 85 },
      { muscleId: 'calves_gastrocnemius', activationPercent: 20 },
    ],
    description: 'Lie face down, curl pad toward glutes.',
  },
  {
    id: 'seated_leg_curl',
    name: 'Seated Leg Curl',
    category: 'hamstrings',
    equipment: ['machine'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 90 },
      { muscleId: 'hamstrings_semitendinosus', activationPercent: 90 },
      { muscleId: 'hamstrings_semimembranosus', activationPercent: 85 },
      { muscleId: 'calves_gastrocnemius', activationPercent: 20 },
    ],
    description: 'Seated, curl pad under thighs. Better hamstring stretch than lying version.',
    tips: 'Slightly superior to lying leg curl due to hip flexion stretching the hamstrings.',
  },
  {
    id: 'nordic_curl',
    name: 'Nordic Hamstring Curl',
    category: 'hamstrings',
    equipment: ['bodyweight'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 95 },
      { muscleId: 'hamstrings_semitendinosus', activationPercent: 95 },
      { muscleId: 'hamstrings_semimembranosus', activationPercent: 90 },
      { muscleId: 'calves_gastrocnemius', activationPercent: 25 },
    ],
    description: 'Kneel, ankles anchored, lower torso forward with control. Eccentric powerhouse.',
    tips: 'Proven to reduce hamstring injury risk. Elite exercise.',
  },
  {
    id: 'good_morning',
    name: 'Good Morning',
    category: 'hamstrings',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'hinge',
    muscles: [
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 80 },
      { muscleId: 'hamstrings_semitendinosus', activationPercent: 75 },
      { muscleId: 'erector_spinae', activationPercent: 85 },
      { muscleId: 'glutes_max', activationPercent: 65 },
    ],
    description: 'Bar on upper back, hinge forward at hips, return to upright.',
  },
  {
    id: 'stiff_leg_deadlift',
    name: 'Stiff-Leg Deadlift',
    category: 'hamstrings',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'hinge',
    muscles: [
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 90 },
      { muscleId: 'hamstrings_semitendinosus', activationPercent: 85 },
      { muscleId: 'erector_spinae', activationPercent: 80 },
      { muscleId: 'glutes_max', activationPercent: 65 },
      { muscleId: 'forearm_flexors', activationPercent: 40 },
    ],
    description: 'Like RDL but legs stay straighter. Greater hamstring stretch.',
  },
  {
    id: 'cable_pull_through',
    name: 'Cable Pull-Through',
    category: 'hamstrings',
    equipment: ['cable'],
    movementType: 'compound',
    forceType: 'hinge',
    muscles: [
      { muscleId: 'glutes_max', activationPercent: 80 },
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 70 },
      { muscleId: 'erector_spinae', activationPercent: 50 },
    ],
    description: 'Face away from cable, pull rope through legs with hip hinge.',
  },
];

// ── LEGS: GLUTES ─────────────────────────────────────────────

const gluteExercises: Exercise[] = [
  {
    id: 'hip_thrust_barbell',
    name: 'Barbell Hip Thrust',
    category: 'glutes',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'hinge',
    muscles: [
      { muscleId: 'glutes_max', activationPercent: 95 },
      { muscleId: 'glutes_med', activationPercent: 50 },
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 50 },
      { muscleId: 'quads_rectus_femoris', activationPercent: 25 },
      { muscleId: 'rectus_abdominis', activationPercent: 20 },
    ],
    description: 'Upper back on bench, bar on hips, thrust hips up to full extension.',
    tips: 'The #1 glute builder. Squeeze hard at the top, chin tucked.',
  },
  {
    id: 'glute_bridge',
    name: 'Glute Bridge',
    category: 'glutes',
    equipment: ['bodyweight', 'barbell'],
    movementType: 'isolation',
    forceType: 'hinge',
    muscles: [
      { muscleId: 'glutes_max', activationPercent: 85 },
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 40 },
      { muscleId: 'rectus_abdominis', activationPercent: 20 },
    ],
    description: 'Lying on back, feet flat, thrust hips up. Can add barbell.',
  },
  {
    id: 'cable_kickback',
    name: 'Cable Kickback',
    category: 'glutes',
    equipment: ['cable'],
    movementType: 'isolation',
    forceType: 'hinge',
    muscles: [
      { muscleId: 'glutes_max', activationPercent: 90 },
      { muscleId: 'glutes_med', activationPercent: 35 },
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 30 },
    ],
    description: 'Ankle strap on low cable, kick leg straight back.',
  },
  {
    id: 'cable_hip_abduction',
    name: 'Cable Hip Abduction',
    category: 'glutes',
    equipment: ['cable'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'glutes_med', activationPercent: 90 },
      { muscleId: 'glutes_min', activationPercent: 75 },
      { muscleId: 'abductors', activationPercent: 70 },
    ],
    description: 'Ankle strap, stand sideways to cable, push leg outward.',
  },
  {
    id: 'hip_abduction_machine',
    name: 'Hip Abduction Machine',
    category: 'glutes',
    equipment: ['machine'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'glutes_med', activationPercent: 85 },
      { muscleId: 'glutes_min', activationPercent: 75 },
      { muscleId: 'abductors', activationPercent: 70 },
    ],
    description: 'Seated machine, push pads outward. Targets upper glutes.',
  },
  {
    id: 'hip_adduction_machine',
    name: 'Hip Adduction Machine',
    category: 'glutes',
    equipment: ['machine'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'adductors', activationPercent: 90 },
      { muscleId: 'glutes_max', activationPercent: 20 },
    ],
    description: 'Seated machine, squeeze pads inward. Targets inner thighs.',
  },
  {
    id: 'sumo_deadlift',
    name: 'Sumo Deadlift',
    category: 'glutes',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'hinge',
    muscles: [
      { muscleId: 'glutes_max', activationPercent: 85 },
      { muscleId: 'quads_rectus_femoris', activationPercent: 60 },
      { muscleId: 'quads_vastus_lateralis', activationPercent: 55 },
      { muscleId: 'adductors', activationPercent: 70 },
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 55 },
      { muscleId: 'erector_spinae', activationPercent: 65 },
      { muscleId: 'traps_upper', activationPercent: 50 },
      { muscleId: 'forearm_flexors', activationPercent: 55 },
    ],
    description: 'Wide stance, hands inside knees, pull. More glute/quad than conventional.',
  },
  {
    id: 'kettlebell_swing',
    name: 'Kettlebell Swing',
    category: 'glutes',
    equipment: ['kettlebell'],
    movementType: 'compound',
    forceType: 'hinge',
    muscles: [
      { muscleId: 'glutes_max', activationPercent: 85 },
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 65 },
      { muscleId: 'erector_spinae', activationPercent: 60 },
      { muscleId: 'rectus_abdominis', activationPercent: 40 },
      { muscleId: 'front_delts', activationPercent: 30 },
      { muscleId: 'forearm_flexors', activationPercent: 40 },
    ],
    description: 'Hip hinge, swing kettlebell to shoulder height with hip drive.',
  },
];

// ── CALVES ───────────────────────────────────────────────────

const calfExercises: Exercise[] = [
  {
    id: 'standing_calf_raise',
    name: 'Standing Calf Raise',
    category: 'calves',
    equipment: ['machine'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'calves_gastrocnemius', activationPercent: 95 },
      { muscleId: 'calves_soleus', activationPercent: 50 },
    ],
    description: 'On calf raise machine, rise up on toes, full ROM.',
    tips: 'Straight legs target gastrocnemius. Pause at bottom and top.',
  },
  {
    id: 'seated_calf_raise',
    name: 'Seated Calf Raise',
    category: 'calves',
    equipment: ['machine'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'calves_soleus', activationPercent: 95 },
      { muscleId: 'calves_gastrocnemius', activationPercent: 30 },
    ],
    description: 'Seated, knees at 90°, push up on toes. Targets soleus specifically.',
    tips: 'Bent knees shift emphasis to soleus. Both seated AND standing are needed.',
  },
  {
    id: 'donkey_calf_raise',
    name: 'Donkey Calf Raise',
    category: 'calves',
    equipment: ['machine', 'bodyweight'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'calves_gastrocnemius', activationPercent: 95 },
      { muscleId: 'calves_soleus', activationPercent: 55 },
    ],
    description: 'Bent at hips, rise on toes. Stretches gastroc maximally.',
  },
  {
    id: 'single_leg_calf_raise',
    name: 'Single-Leg Calf Raise',
    category: 'calves',
    equipment: ['bodyweight', 'dumbbell'],
    movementType: 'isolation',
    forceType: 'push',
    muscles: [
      { muscleId: 'calves_gastrocnemius', activationPercent: 90 },
      { muscleId: 'calves_soleus', activationPercent: 50 },
    ],
    description: 'Single-leg on step, full ROM. Great for fixing calf imbalances.',
  },
  {
    id: 'tibialis_raise',
    name: 'Tibialis Raise',
    category: 'calves',
    equipment: ['bodyweight'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'tibialis_anterior', activationPercent: 95 },
    ],
    description: 'Back against wall, heels out, lift toes up. Prevents shin splints.',
    tips: 'Neglected but crucial for knee health and balanced lower legs.',
  },
];

// ── ABS / CORE ───────────────────────────────────────────────

const absExercises: Exercise[] = [
  {
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    category: 'abs',
    equipment: ['bodyweight'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'rectus_abdominis', activationPercent: 85 },
      { muscleId: 'hip_flexors', activationPercent: 70 },
      { muscleId: 'obliques', activationPercent: 35 },
      { muscleId: 'forearm_flexors', activationPercent: 30 },
    ],
    description: 'Hang from bar, raise legs to parallel or higher. Curl pelvis up.',
  },
  {
    id: 'cable_crunch',
    name: 'Cable Crunch',
    category: 'abs',
    equipment: ['cable'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'rectus_abdominis', activationPercent: 90 },
      { muscleId: 'obliques', activationPercent: 30 },
    ],
    description: 'Kneel facing cable, rope behind head, crunch down toward floor.',
    tips: 'Focus on curling ribcage toward pelvis, not just hinging at hips.',
  },
  {
    id: 'ab_wheel_rollout',
    name: 'Ab Wheel Rollout',
    category: 'abs',
    equipment: ['bodyweight'],
    movementType: 'compound',
    forceType: 'static',
    muscles: [
      { muscleId: 'rectus_abdominis', activationPercent: 95 },
      { muscleId: 'obliques', activationPercent: 50 },
      { muscleId: 'transverse_abdominis', activationPercent: 70 },
      { muscleId: 'lats', activationPercent: 35 },
      { muscleId: 'erector_spinae', activationPercent: 30 },
      { muscleId: 'front_delts', activationPercent: 25 },
    ],
    description: 'Kneel, roll wheel out as far as possible, pull back. Elite core exercise.',
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'abs',
    equipment: ['bodyweight'],
    movementType: 'isolation',
    forceType: 'static',
    muscles: [
      { muscleId: 'transverse_abdominis', activationPercent: 85 },
      { muscleId: 'rectus_abdominis', activationPercent: 65 },
      { muscleId: 'obliques', activationPercent: 50 },
      { muscleId: 'erector_spinae', activationPercent: 40 },
      { muscleId: 'front_delts', activationPercent: 25 },
      { muscleId: 'glutes_max', activationPercent: 20 },
    ],
    description: 'Forearms on ground, body straight, hold position.',
  },
  {
    id: 'side_plank',
    name: 'Side Plank',
    category: 'abs',
    equipment: ['bodyweight'],
    movementType: 'isolation',
    forceType: 'static',
    muscles: [
      { muscleId: 'obliques', activationPercent: 90 },
      { muscleId: 'transverse_abdominis', activationPercent: 60 },
      { muscleId: 'glutes_med', activationPercent: 45 },
      { muscleId: 'rectus_abdominis', activationPercent: 35 },
    ],
    description: 'Side-lying, forearm on ground, hold body straight.',
  },
  {
    id: 'russian_twist',
    name: 'Russian Twist',
    category: 'abs',
    equipment: ['bodyweight', 'medicine_ball'],
    movementType: 'isolation',
    forceType: 'rotation',
    muscles: [
      { muscleId: 'obliques', activationPercent: 85 },
      { muscleId: 'rectus_abdominis', activationPercent: 55 },
      { muscleId: 'transverse_abdominis', activationPercent: 45 },
      { muscleId: 'hip_flexors', activationPercent: 30 },
    ],
    description: 'Seated, lean back, rotate torso side to side with or without weight.',
  },
  {
    id: 'woodchopper',
    name: 'Cable Woodchopper',
    category: 'abs',
    equipment: ['cable'],
    movementType: 'compound',
    forceType: 'rotation',
    muscles: [
      { muscleId: 'obliques', activationPercent: 85 },
      { muscleId: 'rectus_abdominis', activationPercent: 50 },
      { muscleId: 'transverse_abdominis', activationPercent: 45 },
      { muscleId: 'front_delts', activationPercent: 25 },
    ],
    description: 'Rotate torso diagonally pulling cable from high to low or low to high.',
  },
  {
    id: 'pallof_press',
    name: 'Pallof Press',
    category: 'abs',
    equipment: ['cable', 'resistance_band'],
    movementType: 'isolation',
    forceType: 'static',
    muscles: [
      { muscleId: 'obliques', activationPercent: 80 },
      { muscleId: 'transverse_abdominis', activationPercent: 75 },
      { muscleId: 'rectus_abdominis', activationPercent: 50 },
      { muscleId: 'glutes_med', activationPercent: 25 },
    ],
    description: 'Stand perpendicular to cable, press handle out and resist rotation.',
    tips: 'Anti-rotation king. Amazing for core stability and injury prevention.',
  },
  {
    id: 'dead_bug',
    name: 'Dead Bug',
    category: 'abs',
    equipment: ['bodyweight'],
    movementType: 'isolation',
    forceType: 'static',
    muscles: [
      { muscleId: 'transverse_abdominis', activationPercent: 80 },
      { muscleId: 'rectus_abdominis', activationPercent: 65 },
      { muscleId: 'obliques', activationPercent: 40 },
      { muscleId: 'hip_flexors', activationPercent: 35 },
    ],
    description: 'Lying on back, arms up, knees at 90°, extend opposite arm/leg while maintaining back flat.',
  },
  {
    id: 'decline_crunch',
    name: 'Decline Crunch',
    category: 'abs',
    equipment: ['bodyweight'],
    movementType: 'isolation',
    forceType: 'pull',
    muscles: [
      { muscleId: 'rectus_abdominis', activationPercent: 85 },
      { muscleId: 'obliques', activationPercent: 30 },
      { muscleId: 'hip_flexors', activationPercent: 40 },
    ],
    description: 'On decline bench, crunch up. Added resistance via gravity angle.',
  },
  {
    id: 'bicycle_crunch',
    name: 'Bicycle Crunch',
    category: 'abs',
    equipment: ['bodyweight'],
    movementType: 'compound',
    forceType: 'rotation',
    muscles: [
      { muscleId: 'rectus_abdominis', activationPercent: 80 },
      { muscleId: 'obliques', activationPercent: 80 },
      { muscleId: 'hip_flexors', activationPercent: 45 },
      { muscleId: 'transverse_abdominis', activationPercent: 35 },
    ],
    description: 'Lying on back, bring opposite elbow to knee in cycling motion.',
  },
  {
    id: 'dragon_flag',
    name: 'Dragon Flag',
    category: 'abs',
    equipment: ['bodyweight'],
    movementType: 'compound',
    forceType: 'static',
    muscles: [
      { muscleId: 'rectus_abdominis', activationPercent: 95 },
      { muscleId: 'obliques', activationPercent: 55 },
      { muscleId: 'transverse_abdominis', activationPercent: 65 },
      { muscleId: 'hip_flexors', activationPercent: 50 },
      { muscleId: 'lats', activationPercent: 30 },
    ],
    description: 'On bench, grip behind head, lower entire body as one straight unit.',
    tips: 'Advanced. Made famous by Bruce Lee. Ultimate ab exercise.',
  },
];

// ── FULL BODY / OLYMPIC ──────────────────────────────────────

const fullBodyExercises: Exercise[] = [
  {
    id: 'clean_and_press',
    name: 'Clean and Press',
    category: 'olympic',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'quads_rectus_femoris', activationPercent: 70 },
      { muscleId: 'glutes_max', activationPercent: 75 },
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 60 },
      { muscleId: 'front_delts', activationPercent: 80 },
      { muscleId: 'traps_upper', activationPercent: 80 },
      { muscleId: 'erector_spinae', activationPercent: 65 },
      { muscleId: 'triceps_lateral', activationPercent: 50 },
      { muscleId: 'forearm_flexors', activationPercent: 50 },
      { muscleId: 'rectus_abdominis', activationPercent: 45 },
    ],
    description: 'Clean barbell to shoulders, then press overhead. Total body power movement.',
  },
  {
    id: 'power_clean',
    name: 'Power Clean',
    category: 'olympic',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'quads_rectus_femoris', activationPercent: 70 },
      { muscleId: 'glutes_max', activationPercent: 80 },
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 70 },
      { muscleId: 'traps_upper', activationPercent: 85 },
      { muscleId: 'erector_spinae', activationPercent: 70 },
      { muscleId: 'front_delts', activationPercent: 45 },
      { muscleId: 'forearm_flexors', activationPercent: 55 },
      { muscleId: 'calves_gastrocnemius', activationPercent: 35 },
    ],
    description: 'Explosive pull from floor to front rack position.',
  },
  {
    id: 'snatch',
    name: 'Barbell Snatch',
    category: 'olympic',
    equipment: ['barbell'],
    movementType: 'compound',
    forceType: 'pull',
    muscles: [
      { muscleId: 'quads_rectus_femoris', activationPercent: 70 },
      { muscleId: 'glutes_max', activationPercent: 80 },
      { muscleId: 'hamstrings_biceps_femoris', activationPercent: 65 },
      { muscleId: 'traps_upper', activationPercent: 80 },
      { muscleId: 'traps_mid', activationPercent: 60 },
      { muscleId: 'erector_spinae', activationPercent: 70 },
      { muscleId: 'front_delts', activationPercent: 55 },
      { muscleId: 'side_delts', activationPercent: 40 },
      { muscleId: 'forearm_flexors', activationPercent: 50 },
    ],
    description: 'Wide grip explosive pull from floor to overhead in one motion.',
  },
  {
    id: 'thruster',
    name: 'Thruster',
    category: 'full_body',
    equipment: ['barbell', 'dumbbell'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'quads_rectus_femoris', activationPercent: 80 },
      { muscleId: 'quads_vastus_lateralis', activationPercent: 75 },
      { muscleId: 'glutes_max', activationPercent: 70 },
      { muscleId: 'front_delts', activationPercent: 75 },
      { muscleId: 'triceps_lateral', activationPercent: 50 },
      { muscleId: 'rectus_abdominis', activationPercent: 45 },
      { muscleId: 'erector_spinae', activationPercent: 40 },
    ],
    description: 'Front squat into overhead press in one fluid motion.',
  },
  {
    id: 'burpee',
    name: 'Burpee',
    category: 'full_body',
    equipment: ['bodyweight'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'quads_rectus_femoris', activationPercent: 60 },
      { muscleId: 'chest_mid', activationPercent: 50 },
      { muscleId: 'front_delts', activationPercent: 50 },
      { muscleId: 'triceps_lateral', activationPercent: 40 },
      { muscleId: 'hip_flexors', activationPercent: 45 },
      { muscleId: 'rectus_abdominis', activationPercent: 40 },
      { muscleId: 'calves_gastrocnemius', activationPercent: 35 },
    ],
    description: 'Squat, kick feet back, push-up, jump feet forward, jump up.',
  },
  {
    id: 'turkish_getup',
    name: 'Turkish Get-Up',
    category: 'full_body',
    equipment: ['kettlebell', 'dumbbell'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'front_delts', activationPercent: 70 },
      { muscleId: 'rectus_abdominis', activationPercent: 65 },
      { muscleId: 'obliques', activationPercent: 60 },
      { muscleId: 'glutes_max', activationPercent: 55 },
      { muscleId: 'quads_rectus_femoris', activationPercent: 50 },
      { muscleId: 'traps_upper', activationPercent: 50 },
      { muscleId: 'triceps_lateral', activationPercent: 40 },
      { muscleId: 'hip_flexors', activationPercent: 40 },
      { muscleId: 'rotator_cuff', activationPercent: 55 },
    ],
    description: 'From lying down, stand up while keeping weight overhead. Full body stability.',
  },
  {
    id: 'man_maker',
    name: 'Man Maker',
    category: 'full_body',
    equipment: ['dumbbell'],
    movementType: 'compound',
    forceType: 'push',
    muscles: [
      { muscleId: 'chest_mid', activationPercent: 55 },
      { muscleId: 'lats', activationPercent: 50 },
      { muscleId: 'front_delts', activationPercent: 70 },
      { muscleId: 'quads_rectus_femoris', activationPercent: 60 },
      { muscleId: 'glutes_max', activationPercent: 55 },
      { muscleId: 'triceps_lateral', activationPercent: 45 },
      { muscleId: 'rectus_abdominis', activationPercent: 50 },
    ],
    description: 'Push-up, renegade row each side, clean to squat, press overhead. The ultimate combo.',
  },
];

// ── EXPORT ALL ───────────────────────────────────────────────

export const EXERCISE_DATABASE: Exercise[] = [
  ...chestExercises,
  ...backExercises,
  ...shoulderExercises,
  ...bicepsExercises,
  ...tricepsExercises,
  ...forearmExercises,
  ...quadExercises,
  ...hamstringExercises,
  ...gluteExercises,
  ...calfExercises,
  ...absExercises,
  ...fullBodyExercises,
];

// Quick lookup by ID
export const EXERCISE_MAP = new Map(
  EXERCISE_DATABASE.map((e) => [e.id, e])
);

// Quick lookup by category
export const EXERCISES_BY_CATEGORY = EXERCISE_DATABASE.reduce(
  (acc, exercise) => {
    if (!acc[exercise.category]) acc[exercise.category] = [];
    acc[exercise.category].push(exercise);
    return acc;
  },
  {} as Record<string, Exercise[]>
);

// TMLSN Exercise Database loaded
